pkg/consts/qos.go
Enhancements
- Add new memory enhancement numa_exclusive key/value
resolve #3
=> feat(qrm): support memory enhancement numa_exclusive

pkg/consts/pod.go
Features
- Add pod-level net-class default annotation key
Based on out offline discussion, the CRD definition related to Network QoS has been removed for now, and will be added later.
=> feat(qos): add default pod-level net-class annotation key

pkg/plugins/skeleton/generic.go
fix(skeleton): fix serving in stopped gprc server
=> fix(skeleton): fix serving in stopped gprc server

pkg/consts/pod.go, pkg/consts/resource.go
Refactor
Refine api prefixes of resource keys and pod annotations.
=> refactor(api): refine api prefixes of resource keys and pod annotations

config/crd/bases/config.katalyst.kubewharf.io_evictionconfigurations.yaml, pkg/apis/config/v1alpha1/eviction.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, pkg/consts/qos.go
add fields and const related to pod-level rss overuse eviction
=> feat: support pod-level rss overuse evict

go.mod, pkg/plugins/skeleton/generic.go
feat(skeleton): duplicate socket dirs to avoid listening at same sock
=> feat(skeleton): duplicate socket dirs to avoid listening at same sock

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.yaml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, .github/workflows/status-check.yml, Makefile
Chore
- add templates for pull requests and issues
- add status check pipeline
- add ci pipeline
=> chore(*): add some open-source infra config

pkg/apis/node/v1alpha1/types.go
Features
Add values of topology policy to kcnr.
=> feat(api): add values of topology policy to kcnr

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go
Bug fixes
kcc crd definintion includes some list member, if set that with empty list, it may cause checkpoint corrupted, so it should no use omitempty or add some validation.
=> refactor adminqos definition list and map member remove omitempty json flag

pkg/consts/cgroup.go
feat(cgroup): add cgroup version constant variables
=> feat(cgroup): add cgroup version constant variables

pkg/utils/topology_policy.go
Features
Add utils to generate topology policy.
=> feat(kcnr): add utils to generate topology policy

config/crd/bases/node.katalyst.kubewharf.io_customnoderesources.yaml, pkg/apis/node/v1alpha1/types.go
Refactor
Make the resources of kcnr status optional.
=> refactor(api): make the resources of kcnr status optional

pkg/metric/pod/pod.go
enhancements
add custom metric for pod-level
=> add pod-level metric pod usage

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Enhancements
this PR adds some dynamic configuration related to load eviction's dynamic threshold feature
=> feat(eviction): load eviction support dynamic threshold

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Chore
keep naming style in line with existing field
=> refactor(qrm): keep naming style in line with existing field

pkg/metric/node/node.go, pkg/metric/pod/pod.go
enhancements
add more metrics for kcmas
=> add more name names for kcmas

pkg/plugins/skeleton/generic.go
fix(skeleton): fix skeleton log not only for reporter
=> fix(skeleton): fix skeleton log not only for reporter

pkg/metric/pod/pod.go
Enhancements
add memory usage custom metric name
=> add memory usage metric name

pkg/apis/workload/v1alpha1/types.go
Enhancements
Add cpu usage ratio indicator metric for rama policy
=> add indicator cpu usage ratio

pkg/plugins/skeleton/generic.go
Enhancements
PluginRegistrationWrapper inherit GenericPlugin directly.
=> PluginRegistrationWrapper inherit GenericPlugin directly

pkg/consts/spd.go, pkg/utils/topology_policy.go
Features
spd baseline const definition
=> add spd baseline related const

pkg/consts/overcommit.go, pkg/consts/qos.go, pkg/consts/spd.go, pkg/consts/vpa.go
docs
add detailed comments for katalyst enhancements and other consts
=> add detailed comments for katalyst enhancements and other consts

pkg/consts/qos.go, pkg/consts/qrm.go
related to this [issue](https://github.com/kubewharf/katalyst-core/issues/216)
=> feat(qrm): Support for OOM priority as a QoS enhancement

config/crd/bases/workload.katalyst.kubewharf.io_serviceprofiledescriptors.yaml, pkg/apis/workload/v1alpha1/types.go, pkg/apis/workload/v1alpha1/zz_generated.deepcopy.go, pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go
=> rename baselineRatio to baselinePercent

pkg/consts/spd.go
=> refine(spd): update consts

config/crd/bases/tide.katalyst.kubewharf.io_tidenodepools.yaml, pkg/apis/tide/v1alpha1/types.go
=> misc: fix shortname for tidenodepool

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
=> feat: add ThresholdMetToleranceDuration

pkg/consts/resource.go
Enhancements
add memory bandwidth resource to support memory bandwidth report to cnr
=> add memory bandwidth resource

pkg/apis/workload/v1alpha1/types.go
=> feat: new ServiceSystemIndicatorName

pkg/metric/consts.go
Enhancements
This PR supports the p95 aggregate function for kcmas.
=> enhancement(kcmas): aggregate function p95

pkg/consts/resource.go
feat(qrm): add ResourceAnnotationKeyNICNetNSName
=> feat(qrm): add ResourceAnnotationKeyNICNetNSName

pkg/consts/overcommit.go
Enhancements
add overcommit constants used in https://github.com/kubewharf/katalyst-core/pull/472
=> add realtime overcommit constants

pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
fix(adminqos): add deepcopy for LoadLowerBoundRatio
=> fix(adminqos): add deepcopy for LoadLowerBoundRatio

pkg/consts/pod.go
=> support qrm vpa admit

pkg/consts/pod.go
=> feat(qrm): rename inplace update key

pkg/metric/node/node.go, pkg/metric/pod/pod.go
Features
Add cpu usage ratio for pod and node custom metrics.
=> feat(kcmas): add cpu usage ratio for pod and node custom metrics

pkg/apis/autoscaling/v1alpha2/register.go
=> remove ihpa for 1.18.10

.github/workflows/ci.yml, cmd/inlinecheck/main.go, pkg/apis/config/v1alpha1/adminqos.go
=> chore(ci): add inlinecheck

pkg/consts/pod.go
=> add numa bind result pod annotation key

pkg/consts/pod.go
=> add nic selection result pod annotation

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, config/crd/bases/node.katalyst.kubewharf.io_customnoderesources.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
=> add MinIgnoredReclaimedResourceForReport to avoid resource fragmentation

pkg/metric/node/node.go
Features
Add cpu total and cpu usage metric for kcmas.
=> add cpu total and cpu usage metric for kcmas

.github/workflows/ci.yml, .github/workflows/status-check.yml, pkg/apis/config/v1alpha1/adminqos.go
=> feat: add control knob of cpu quota and cpu size

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
=> feat(eviction): support rootfs overuse eviction

pkg/metric/node/node.go, pkg/metric/pod/pod.go
- add pod level and numa level memory bandwidth related metrics
=> feat(consts): add memory bandwidth related metric

pkg/apis/node/v1alpha1/register.go
=> fix(npd): fix resource name of npd to its plural form

pkg/utils/eviction.go
Enhancements
Add CNRConditionQoSLevelEffectSeparator constant to separate QoS Level and CNR effects in conditions
=> feat(consts): add separator constant for CNR condition effects

config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml, pkg/apis/config/v1alpha1/adminqos.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Features
add numa cpu eviction candidate count param
=> feat(cpu-eviction) add numa cpu eviction candidate count param

pkg/apis/config/v1alpha1/adminqos.go
Enhancements
adding ReclaimedGracePeriod
improve mem.eviction efficiency
None
=> MemoryPressureEvictionConfig: adding ReclaimedGracePeriod
